// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAOlhEFe2skR9jFjKT4c8qM_qCxiSFjLMc',
    appId: '1:836573166533:android:100aa66e6104aea620e9ac',
    messagingSenderId: '836573166533',
    projectId: 'my-product-app-5a0eb',
    storageBucket: 'my-product-app-5a0eb.firebasestorage.app',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBp6jszcqqQjE-uuQfG0r6chTNcerIoNoc',
    appId: '1:836573166533:web:99ce348c3688c6a720e9ac',
    messagingSenderId: '836573166533',
    projectId: 'my-product-app-5a0eb',
    authDomain: 'my-product-app-5a0eb.firebaseapp.com',
    storageBucket: 'my-product-app-5a0eb.firebasestorage.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBNyPfYivJyjsi0r2--WNrQVd1LHpHKdao',
    appId: '1:836573166533:ios:907b43f5be3068e420e9ac',
    messagingSenderId: '836573166533',
    projectId: 'my-product-app-5a0eb',
    storageBucket: 'my-product-app-5a0eb.firebasestorage.app',
    iosBundleId: 'com.example.myProductApp',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBNyPfYivJyjsi0r2--WNrQVd1LHpHKdao',
    appId: '1:836573166533:ios:907b43f5be3068e420e9ac',
    messagingSenderId: '836573166533',
    projectId: 'my-product-app-5a0eb',
    storageBucket: 'my-product-app-5a0eb.firebasestorage.app',
    iosBundleId: 'com.example.myProductApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBp6jszcqqQjE-uuQfG0r6chTNcerIoNoc',
    appId: '1:836573166533:web:8db948fb159316d220e9ac',
    messagingSenderId: '836573166533',
    projectId: 'my-product-app-5a0eb',
    authDomain: 'my-product-app-5a0eb.firebaseapp.com',
    storageBucket: 'my-product-app-5a0eb.firebasestorage.app',
  );

}